services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "pettiville/configserver:s1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  invoicedb:
    container_name: invoicedb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: invoicedb
    volumes:
      - invoicedb_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config

  userdb:
    container_name: userdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: userdb
    volumes:
      - userdb_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config

  invoice:
    image: "pettiville/invoice:s1"
    container_name: invoice-ms
    ports:
      - "8080:8080"
    depends_on:
      invoicedb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://invoicedb:3306/invoicedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_APPLICATION_NAME: invoice
      # Flyway configurations
      SPRING_FLYWAY_LOCATIONS: classpath:/db/migration
      SPRING_FLYWAY_SQL-MIGRATION-SUFFIXES: .sql
      SPRING_FLYWAY_URL: jdbc:mysql://invoicedb:3306/invoicedb
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: root
      SPRING_FLYWAY_BASELINE-VERSION: 0.0
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  user:
    image: "pettiville/user:s1"
    container_name: user-ms
    ports:
      - "8081:8081"
    depends_on:
      userdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://userdb:3306/userdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_APPLICATION_NAME: user
      # Flyway configurations
      SPRING_FLYWAY_LOCATIONS: classpath:/db/migration
      SPRING_FLYWAY_SQL-MIGRATION-SUFFIXES: .sql
      SPRING_FLYWAY_URL: jdbc:mysql://userdb:3306/userdb
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: root
      SPRING_FLYWAY_BASELINE-VERSION: 0.0
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  apettigrew:
    driver: "bridge"


volumes:
  invoicedb_data:
  userdb_data: