{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - name: {{ .Values.appLabel }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
        {{- if .Values.appname_enabled }}
        - name: SPRING_APPLICATION_NAME
          value: {{ .Values.appName }}
        {{- end }}
        {{- if .Values.profile_enabled }}
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_PROFILES_ACTIVE
        {{- end }}
        {{- if .Values.config_enabled }}
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_CONFIG_IMPORT
        {{- end }}
        {{- if .Values.eureka_enabled }}
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        {{- end }}
        {{- if .Values.resourceserver_enabled }}
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
        {{- end }}
        {{- if .Values.otel_enabled }}
        - name: JAVA_TOOL_OPTIONS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: JAVA_TOOL_OPTIONS
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_METRICS_EXPORTER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: OTEL_METRICS_EXPORTER
        - name: OTEL_LOGS_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: OTEL_LOGS_EXPORTER
        - name: OTEL_SERVICE_NAME
          value: {{ .Values.appName }}
        {{- end }}
        {{- if .Values.rabbit_enabled }}
        - name: SPRING_RABBITMQ_HOST
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_RABBITMQ_HOST
        {{- end }}
        {{- if .Values.rabbit_enabled }}
        - name: SPRING_RABBITMQ_PORT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_RABBITMQ_PORT
        {{- end }}
        {{- if .Values.rabbit_enabled }}
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_RABBITMQ_USERNAME
        {{- end }}
        {{- if .Values.rabbit_enabled }}
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_RABBITMQ_PASSWORD
        {{- end }}
        {{- if .Values.keycloak_enabled }}
        - name: KEYCLOAK_SERVERURL
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOAK_SERVERURL
        {{- end }}
        {{- if .Values.keycloak_enabled }}
        - name: KEYCLOAK_REALM
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOAK_REALM
        {{- end }}
        {{- if .Values.keycloak_enabled }}
        - name: KEYCLOAK_CLIENTID
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOAK_CLIENTID
        {{- end }}
        {{- if .Values.keycloak_enabled }}
        - name: KEYCLOAK_USERNAME
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOAK_USERNAME
        {{- end }}
        {{- if .Values.keycloak_enabled }}
        - name: KEYCLOAK_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOAK_PASSWORD
        {{- end }}
        {{- if .Values.keycloak_enabled }}
        - name: KEYCLOAK_AUTHSERVERURL
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOAK_AUTHSERVERURL
        {{- end }}
        {{- if .Values.keycloak_enabled }}
        - name: KEYCLOAK_APPCLIENTID
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOAK_APPCLIENTID
        {{- end }}
        {{- if .Values.keycloak_enabled }}
        - name: KEYCLOAK_APPCLIENTSECRET
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOAK_APPCLIENTSECRET
        {{- end }}
{{- end -}}