# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: users-deployment
serviceName: users
appLabel: users
appName: users

replicaCount: 1

image:
  repository: pettiville/users
  tag: v1

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
rabbit_enabled: true
keycloak_enabled: true